### ISSUE TITLE
How to connect nodes that are not connected

### ISSUE THREAD

**Issue by haziqj** [indiraputeri/stan_bym#1]
I just checked my previous scripts. I just did a manual connection. Which means I need to know what the ids of these nodes to be connected are. There must be a smarter way to do this, but if there's not too many nodes that need connecting then this should be fine.

```r
neighbors <- poly2nb(nc_sp, row.names = nc_sp$id)

# Connect Mukim Kota Batu (id = 41) to Mukim Labu (id = 14)
mkb <- which(attr(neighbors, "region.id") == 41)
mlb <- which(attr(neighbors, "region.id") == 14)

neighbors[[mkb]] <- c(neighbors[[mkb]], mlb)
neighbors[[mlb]] <- c(neighbors[[mlb]], mkb)
```

As you can see it's just a hack to add the neighbour information via subsetting `[[id]]` and adding integer vector of neighbour nodes.

**Comment by indiraputeri** [comment]
thank you, Dr. Haziq. I already update the code using your previous example: 

`lop.nb[[608]] <- 607L   # Desa Gili Indah to Pemenang Barat
lop.nb[[571]] <- 566L   # Lawang island to Desa Sugian
lop.nb[[567]] <- 566L   # Sulat island to Desa Sugian
lop.nb[[554]] <- 557L   # Gili Petagan to Desa Padak Guar
lop.nb[[548]] <- 557L   # Gili Kondo to Desa Padak Guar
lop.nb[[327]] <- 335L   # Pulau Maringkik to Desa Tanjung Luar
lop.nb[[324]] <- 335L   # Pulau Maringkik to Desa Tanjung Luar
lop.nb[[321]] <- 335L   # Pulau Maringkik to Desa Tanjung Luar
lop.nb[[318]] <- 320L   # Gili Sunut to Desa Sekaroh
lop.nb[[317]] <- 320L   # Gili Sunut to Desa Sekaroh
lop.nb[[61]]  <- 64L     # Gili Gede Indah to Desa Sekotong Barat`

the output can be seen in output/lop_neighpolyconnected in stan_bym repo
